version: "3"
services:
  app:
    build: .
    ports: 
      - "3000:3000"
    volumes: 
      - ".:/goAuth"
    tty: true
    stdin_open: true
    environment: 
      - GO111MODULE=on
      - GOOGLE_CLIENT=$GOOGLE_CLIENT
      - GOOGLE_SECRET=$GOOGLE_SECRET