version: "3"
services:
  app:
    build: .
    volumes: 
      - ".:/goAuth"
    tty: true
    stdin_open: true
    environment: 
      - GO111MODULE=on
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_SECRET_ID=$GOOGLE_SECRET_ID